(feat) add spinner and lock browser during save process
EyeSeeTea/project-monitoring-app pull request #454
Opened 2022-06-16 19:06 UTC by Offem-Peter

### :pushpin: References

* **Issue:** Closes [[https://app.clickup.com/t/2er5du8](https://app.clickup.com/t/2er5du8)] #

2022-06-17 11:21 UTC, tokland commented
I've set the PR as fraft and removed the reviewers, as @adrianq has asked for some changes. @Offem-Peter, set "ready for review" and re-add us as reviewerers when the task is completed, thx!

2022-06-20 10:46 UTC, tokland requested changes

2022-06-20 10:46 UTC, tokland commented on src/components/steps/save/SaveStep.tsx
>      const checkExistingDataAndSave = React.useCallback(async () => {
Check the linting warnings (shown on `yarn start` output or the JS console or explit `yarn lint`):

```Line 79:8:  React Hook React.useCallback has a missing dependency: 'loading'. Either include it or remove the dependency array```

2022-06-20 10:46 UTC, tokland commented on src/components/steps/save/SaveStep.tsx
> +                return save(loading);
There is another save in `saveAndSendExistingDataMessage`, use loading also there (thus, the `loading` argument of `save`  won't be optional)

2022-06-20 10:46 UTC, tokland commented on src/components/steps/save/SaveStep.tsx
> -            setSaving(false);
If there is an error, `loading` should be also hidden.

2022-06-20 10:46 UTC, tokland commented on src/components/steps/save/SaveStep.tsx
> +            try {
You can add a loadin.show here in case the caller did not call it.

2022-06-22 20:27 UTC, Offem-Peter commented
@tokland changes implemented.

2022-06-23 11:33 UTC, tokland commented
Ok. Peter, you ask for a re-review with the github interface, the sync button:

![image](https://user-images.githubusercontent.com/24643/175289253-6bfd36fa-bc5e-4ea0-9f9c-d37b49560065.png)

2022-06-23 11:45 UTC, tokland approved these changes
Just a couple of details I committed, otherwise, all good. Changes I made:

- The argument `loading` of save is not necessary, as the `useSave` hook can get the variable itself.
- Note that after `existingDataCheck`, if the result was "with-values", we need to hide the loading mask so the user can interact with the existing-data-dialog.

2022-08-23 18:30 UTC, merged